[versions]
# libraries

# plugins
gradleIntelliJPlugin = "2.10.2"
kotlin = "2.2.21"
grammarkit = "2022.3.2.2"
changelog = "2.4.0"
qodana = "0.1.13"
kover = "0.9.3"

[libraries]
junit = { module = "junit:junit", version = "4.13.2" }
test4j = { module = "org.opentest4j:opentest4j", version = "1.3.0" }

[plugins]
gradleIntelliJPlugin = { id = "org.jetbrains.intellij.platform", version.ref = "gradleIntelliJPlugin" }
kotlin = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
changelog = { id = "org.jetbrains.changelog", version.ref = "changelog" }
kover = { id = "org.jetbrains.kotlinx.kover", version.ref = "kover" }
qodana = { id = "org.jetbrains.qodana", version.ref = "qodana" }
grammarkit = { id = "org.jetbrains.grammarkit", version.ref = "grammarkit" }
